# -*- coding: utf-8 -*-
"""Covid-analisi_terapia_intensiva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GKZR3W3Xd6v3sWTX0EveLltktQaX-0mK
"""

#!pip install geopandas

import pandas as pd
import numpy as np
import geopandas as gpd

data_regioni = pd.read_csv("https://github.com/pcm-dpc/COVID-19/raw/master/dati-regioni/dpc-covid19-ita-regioni.csv")
data_regioni = data_regioni[data_regioni['data'] ==max(data_regioni['data']) ]
df = data_regioni[['denominazione_regione', 'terapia_intensiva']]
df['terapia_intensiva'] = df['terapia_intensiva'].fillna(0)

df.head()

somma = int(sum(df.terapia_intensiva[df.denominazione_regione == "P.A. Trento"], df.terapia_intensiva[df.denominazione_regione == "P.A. Bolzano"]))

df['denominazione_regione'][df.denominazione_regione == "Friuli Venezia Giulia"] = "Friuli-Venezia Giulia"

df_trentino = pd.DataFrame([{'denominazione_regione':"Trentino-Alto Adige", 
                             "terapia_intensiva": somma}])
df = pd.concat([df, df_trentino], ignore_index=True)

mappa = gpd.read_file("https://raw.githubusercontent.com/vincnardelli/covid19-italia/master/regioni/regioni_italiane.geojson")
mappa = mappa.merge(df, left_on='description', right_on='denominazione_regione', how='left')

nomi_regioni = ["Abruzzo", "Basilicata", "Calabria", "Campania", 
                "Emilia-Romagna", "Friuli-Venezia Giulia", "Lazio", "Liguria", 
                "Lombardia", "Marche", "Molise", "Piemonte", "Puglia",
                "Sardegna", "Sicilia", "Toscana", "Umbria", "Valle d'Aosta", 
                "Veneto", "Trentino-Alto Adige"] 

posti_attuali = [133, 73, 152, 427, 
                 516, 175, 747, 209,
                 983, 127, 34, 367, 366, 
                 175, 538, 415, 70, 20, 
                 825, 106]

df_attuali = pd.DataFrame()
df_attuali['description'] = nomi_regioni
df_attuali['posti_attuali'] = posti_attuali

mappa = mappa.merge(df_attuali, on='description', how='left')
mappa['perc'] = mappa['terapia_intensiva']/mappa['posti_attuali']*100
mappa.to_file("terapia_intensiva.geojson", driver='GeoJSON')