name: Update csv

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        dir
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python update.py
        dir
        var=$(date +"%FORMAT_STRING")
        now=$(date +"%d_%m_%Y %H:%M:%S")
        echo "Run at ${now}" >> workflow.log
        
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add .
        set +e  # Grep succeeds with nonzero exit codes to show results.
        git status | grep modified
        if [ $? -eq 0 ]
        then
            set -e
            git commit -am "update"
            git push
        else
            set -e
            echo "No changes since last run"
        fi
      shell: bash
