name: Run model

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      id: build
      run: |
        cd model
        docker build --tag covstat_model .
        
    - name: Run docker
      id: run
      run: |
        cd model
        docker run --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp covstat_model python model.py
        ls
        mv modello.csv ../data/modello.csv
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update model
