name: Generazione mappa

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      id: build
      run: |
        cd spatial
        docker build --tag spatial_covstat .
        
    - name: Run docker
      id: run
      run: |
        cd spatial
        docker run --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp spatial_covstat python code.py
        ls
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update
