name: Aggiornamento dashboard vaccini

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      id: build
      run: |
        cd vaccini
        docker build --tag covstat_vaccini .
        
    - name: Run docker
      id: run
      run: |
        cd vaccini
        docker run --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp covstat_vaccini python covstat_vaccini.py
        ls
        mv *.csv ../data/*.csv

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Aggiornamento vaccini
